"""add onboarding fields

Revision ID: 19a84c77f79c
Revises: 
Create Date: 2026-02-25 00:38:38.200677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19a84c77f79c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transcripts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('transcripts')
        batch_op.drop_column('onboarding_state')

    # ### end Alembic commands ###
