"""add profile.locale

Revision ID: cae1bde8aad1
Revises: 0e724b485a05
Create Date: 2026-06-20 03:29:43.854674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae1bde8aad1'
down_revision = '0e724b485a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locale', sa.String(length=8), server_default='en', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('locale')

    # ### end Alembic commands ###
